services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      PGUSER: postgres
      POSTGRES_DB: medium
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: