version: '3.8'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "PGPASSWORD=$${POSTGRES_PASSWORD} psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1;' || exit 1"
        ]
      interval: 1s
      timeout: 5s
      retries: 10
    # This allows accessing externally from "localhost" in addition to "127.0.0.1"
    ports:
      - ${POSTGRES_PORT}:5432

  app:
    image: node:21-bullseye
    restart: unless-stopped

    volumes:
      - ..:/workspaces:cached
      - ../scripts:/scripts:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    # depends_on:
    #   - db
    # environment:
    #   - POSTGRES_HOST=db # connect to the Postgres container with Docker Networking
    #   - POSTGRES_PORT=5432 # use internal port of Postgres container

volumes:
  postgres-data:
