version: '3.8'

x-common:
  &commmon
  build:
    context: ..
    dockerfile: docker/Dockerfile
  depends_on:
    db:
      condition: service_healthy
  env_file:
    - ../environments/local/.env.db
    - ../environments/local/.env.app
  environment:
    - POSTGRES_HOST=db
    - POSTGRES_PORT=${POSTGRES_PORT}
  volumes:
    - ..:/app


services:
  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      timeout: 30s
      retries: 10
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  db-init:
    <<: *commmon
    command: ["bun", "db:migrate", "&&", "bun", "db:seed"]
    restart: no

  app:
    <<: *commmon
    restart: unless-stopped
    command: ["bun", "dev"]
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - ${APP_PORT}:${APP_PORT}

volumes:
  postgres-data:

