name: Lint, format, and test

on:
  pull_request:
    branches: [main]
    paths:
      # only typescript/json should be linted and formatted
      - "**.json"
      - "**.ts"
  push:
    branches: [main]
    paths:
      # only typescript/json should be linted and formatted
      - "**.json"
      - "**.ts"
  workflow_dispatch:

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: 1.2.2

      - name: Run Biome
        run: biome ci . --organize-imports-enabled=false

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Test the code
        run: bun test
