name: Lint, format, and test

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Lint and format the code
        run: bunx biome ci --linter-enabled=true --formatter-enabled=true .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Test the code
        run: bun test
