# Run tests (e.g. build) on pull requests

name: tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun: ['1.1.43', 'latest']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun: ['1.1.43', 'latest']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}
      - name: Install dependencies
        run: bun install
      - name: Run API Tests
        run: bun run test:api
      - name: Run Unit Tests
        run: bun run test:unit

  test-typesafety:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun: ['1.1.43', 'latest']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}
      - name: Install dependencies
        run: bun install
      - name: Run Type Safety Tests
        run: bun run typecheck